//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.infomanager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DailyType()
        {
            this.Daily = new HashSet<Daily>();
            this.DailyTypeExtra = new HashSet<DailyTypeExtra>();
            this.DailyTypeOption = new HashSet<DailyTypeOption>();
        }
    
        public int typeId { get; set; }
        public Nullable<int> parentTypeId { get; set; }
        public Nullable<int> nextTypeId { get; set; }
        public string internalTitle { get; set; }
        public bool isActive { get; set; }
        public bool isFavorite { get; set; }
        public int sortOrder { get; set; }
        public Nullable<int> defaultOptionId { get; set; }
        public string iconCss { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daily> Daily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyTypeExtra> DailyTypeExtra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyTypeOption> DailyTypeOption { get; set; }
    }
}
