//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.infomanager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkVehicle
    {
        public int vehicleId { get; set; }
        public string numberplate { get; set; }
        public int typeId { get; set; }
        public bool isArchived { get; set; }
        public string lastLocation { get; set; }
        public string remark { get; set; }
    
        public virtual WorkVehicleType WorkVehicleType { get; set; }
    }
}
