//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.infomanager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Work()
        {
            this.WorkTask = new HashSet<WorkTask>();
            this.WorkTaskDocumentation = new HashSet<WorkTaskDocumentation>();
        }
    
        public System.Guid workId { get; set; }
        public Nullable<System.DateTime> startDateTime { get; set; }
        public Nullable<System.DateTime> endDateTime { get; set; }
        public string remark { get; set; }
        public string systemRemark { get; set; }
        public Nullable<int> status { get; set; }
        public System.DateTime createDateTime { get; set; }
        public int createUserId { get; set; }
        public Nullable<int> deleteUserId { get; set; }
        public Nullable<System.DateTime> deleteDateTime { get; set; }
        public Nullable<System.DateTime> finishedDateTime { get; set; }
        public Nullable<int> finishedUserId { get; set; }
        public Nullable<System.DateTime> archiveDateTime { get; set; }
        public Nullable<int> archiveUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkTask> WorkTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkTaskDocumentation> WorkTaskDocumentation { get; set; }
    }
}
