//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceLine
    {
        public int lineId { get; set; }
        public int financeId { get; set; }
        public int counterAccountId { get; set; }
        public string title { get; set; }
        public decimal amount { get; set; }
        public System.DateTime createDateTime { get; set; }
        public int createUserId { get; set; }
        public Nullable<System.DateTime> validateDateTime { get; set; }
    
        public virtual Finance Finance { get; set; }
        public virtual FinanceAccount FinanceAccount { get; set; }
    }
}
