//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinDummy
    {
        public long lineId { get; set; }
        public System.DateTime registerDateTime { get; set; }
        public string text { get; set; }
        public Nullable<decimal> accSalary { get; set; }
        public Nullable<decimal> accBudget { get; set; }
        public Nullable<decimal> accSaving { get; set; }
        public Nullable<decimal> accCash { get; set; }
        public Nullable<decimal> accCoop { get; set; }
        public Nullable<decimal> accHoliday { get; set; }
        public Nullable<int> accountId { get; set; }
        public string remark { get; set; }
    }
}
