//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoEntry
    {
        public int entryId { get; set; }
        public int infoId { get; set; }
        public int typeId { get; set; }
        public string title { get; set; }
        public string entry { get; set; }
        public int sortOrder { get; set; }
        public string remark { get; set; }
        public System.DateTime createDateTime { get; set; }
        public Nullable<int> createUserId { get; set; }
    
        public virtual Info Info { get; set; }
        public virtual InfoEntryType InfoEntryType { get; set; }
    }
}
