//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infomanager.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class infomanager_dk_db_mainEntities : DbContext
    {
        public infomanager_dk_db_mainEntities()
            : base("name=infomanager_dk_db_mainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Daily> Daily { get; set; }
        public virtual DbSet<DailyInfo> DailyInfo { get; set; }
        public virtual DbSet<DailyType> DailyType { get; set; }
        public virtual DbSet<DailyTypeExtra> DailyTypeExtra { get; set; }
        public virtual DbSet<DailyTypeOption> DailyTypeOption { get; set; }
        public virtual DbSet<Finance> Finance { get; set; }
        public virtual DbSet<FinanceAccount> FinanceAccount { get; set; }
        public virtual DbSet<FinanceAccountType> FinanceAccountType { get; set; }
        public virtual DbSet<FinanceLine> FinanceLine { get; set; }
        public virtual DbSet<Info> Info { get; set; }
        public virtual DbSet<InfoCategory> InfoCategory { get; set; }
        public virtual DbSet<InfoEntry> InfoEntry { get; set; }
        public virtual DbSet<InfoEntryType> InfoEntryType { get; set; }
        public virtual DbSet<InfoTag> InfoTag { get; set; }
        public virtual DbSet<SysUser> SysUser { get; set; }
        public virtual DbSet<SysUserTimesheet> SysUserTimesheet { get; set; }
        public virtual DbSet<Work> Work { get; set; }
        public virtual DbSet<WorkAddress> WorkAddress { get; set; }
        public virtual DbSet<WorkStatusEnum> WorkStatusEnum { get; set; }
        public virtual DbSet<WorkTask> WorkTask { get; set; }
        public virtual DbSet<WorkTaskDocumentation> WorkTaskDocumentation { get; set; }
        public virtual DbSet<WorkTaskTemplate> WorkTaskTemplate { get; set; }
        public virtual DbSet<WorkTaskType> WorkTaskType { get; set; }
        public virtual DbSet<WorkVehicle> WorkVehicle { get; set; }
        public virtual DbSet<WorkVehicleType> WorkVehicleType { get; set; }
        public virtual DbSet<vw_Daily_Days> vw_Daily_Days { get; set; }
        public virtual DbSet<vw_Daily_Overview> vw_Daily_Overview { get; set; }
        public virtual DbSet<vw_Daily_Statistics> vw_Daily_Statistics { get; set; }
        public virtual DbSet<vw_DailyType_Tree> vw_DailyType_Tree { get; set; }
    }
}
