//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DailyType_Tree
    {
        public Nullable<int> typeId { get; set; }
        public Nullable<int> parentTypeId { get; set; }
        public Nullable<int> nextTypeId { get; set; }
        public string internalTitle { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isFavorite { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<int> defaultOptionId { get; set; }
        public string iconCss { get; set; }
        public string description { get; set; }
        public string optionList { get; set; }
        public Nullable<int> qtyOptions { get; set; }
        public string breadcrum { get; set; }
    }
}
