//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infomanager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTaskType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkTaskType()
        {
            this.WorkTask = new HashSet<WorkTask>();
            this.WorkTaskTemplate = new HashSet<WorkTaskTemplate>();
        }
    
        public int typeId { get; set; }
        public string actionType { get; set; }
        public string internalTitle { get; set; }
        public string btnStartText { get; set; }
        public string btnEndText { get; set; }
        public string icon { get; set; }
        public Nullable<int> requiredFields { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkTask> WorkTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkTaskTemplate> WorkTaskTemplate { get; set; }
    }
}
