//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infomanager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkTask()
        {
            this.WorkTaskDocumentation = new HashSet<WorkTaskDocumentation>();
        }
    
        public System.Guid taskId { get; set; }
        public System.Guid workId { get; set; }
        public int typeId { get; set; }
        public int sortOrder { get; set; }
        public Nullable<System.DateTime> startDateTime { get; set; }
        public Nullable<System.DateTime> endDateTime { get; set; }
        public string addressText { get; set; }
        public string vehicleText { get; set; }
        public string vehicleNumberplate { get; set; }
        public string linkNumberplate { get; set; }
        public string dollyNumberplate { get; set; }
        public string trailerNumberplate { get; set; }
        public string remark { get; set; }
        public string systemRemark { get; set; }
        public System.DateTime createDateTime { get; set; }
        public int createUserId { get; set; }
        public Nullable<System.DateTime> deleteDateTime { get; set; }
        public Nullable<int> deleteUserId { get; set; }
        public Nullable<bool> isFinished { get; set; }
        public byte reportColumnNumber { get; set; }
        public string transportId { get; set; }
        public string freighterSetup { get; set; }
        public string addressSetup { get; set; }
    
        public virtual Work Work { get; set; }
        public virtual WorkTaskType WorkTaskType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkTaskDocumentation> WorkTaskDocumentation { get; set; }
    }
}
