//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.infomanager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinanceAccount()
        {
            this.FinanceLine = new HashSet<FinanceLine>();
        }
    
        public int accountId { get; set; }
        public Nullable<int> parentAccountId { get; set; }
        public string typeId { get; set; }
        public string title { get; set; }
        public decimal sumInitial { get; set; }
        public decimal sumMovement { get; set; }
        public Nullable<decimal> sumActual { get; set; }
        public string sumGroupTitle { get; set; }
        public Nullable<byte> C_lvl { get; set; }
        public string C_sortOrder { get; set; }
        public string C_title { get; set; }
    
        public virtual FinanceAccountType FinanceAccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanceLine> FinanceLine { get; set; }
    }
}
